# dataset: gtzan
# sr: 22050
# slice_sec: 3
# batch_size: 64
# epochs: 40
# lr: 1e-3
# optimizer: adam
# augment: true
# n_mels: 128
# n_fft: 2048
# hop_length: 512
# model: cnn_baseline

audio:
  hop_length: 512

augmentation:
  AddGaussianNoise:
    min_amplitude: 0.001
    max_amplitude: 0.01
    p: 0.3
  TimeStretch:
    min_rate: 0.9
    max_rate: 1.1
    p: 0.3
  PitchShift:
    min_semitones: -2
    max_semitones: 2
    p: 0.3
  Shift:
    min_shift: -0.2
    max_shift: 0.2
    p: 0.2

dataset:
  csv_path: "data/processed/gtzan/metadata.csv"

model:
  num_classes: 10

training:
  epochs: 40
  batch_size: 64
  learning_rate: 0.001
  num_workers: 2
  seed: 42